apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      nodeSelector:
        {{- with .Values.nodeSelector }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ .Values.name }}-container
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- with .Values.db.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}

