name: database
replicaCount: 1
image: postgres:15-alpine
nodeSelector: {app2: database}
containerPort: 5432
service:
  port: 5432
  targetPort: 5432
db:
  env:
  - name: POSTGRES_PASSWORD
    value: "yourpassword"
  - name: POSTGRES_DB
    value: "postgres"
  - name: POSTGRES_USER
    value: "postgres"
pvcName: db-pvc
